language: haskell

env:
  matrix:
    - HPVER=2014.2.0.0 CABALVER=1.18
    - GHCVER=7.6.3 CABALVER=1.18
    - GHCVER=7.8.4 CABALVER=1.18
    - GHCVER=7.10.2 CABALVER=1.22
    - GHCVER=head CABALVER=head
  global:
    - UBUNTU_PKGS="libcairo2-dev"
    - HEAD_DEPS="diagrams-core diagrams-lib active diagrams-solve monoid-extras dual-tree statestack"
    - EXTRA_DEPS_PRE="gtk2hs-buildtools Cabal"

matrix:
  allow_failures:
    - env: HPVER=2013.2.0.0 CABALVER=1.18
    - env: GHCVER=head CABALVER=head

before_install:
  - git clone http://github.com/diagrams/diagrams-travis travis
  - source travis/scripts/set_env.sh
  - ./travis/scripts/before_install.sh

install: ./travis/scripts/install.sh

script: ./travis/scripts/script.sh

notifications:
  email: false
  irc:
    channels:
      - irc.freenode.org#diagrams
    skip_join: true
    template:
      - "\x0313diagrams-cairo\x03/\x0306%{branch}\x03 \x0314%{commit}\x03 %{build_url} %{message}"
